### ISSUE TITLE
Observable ojs not working

### ISSUE THREAD

**Issue by jeffkimbrel** [jthomasmock/quarto-2hr-webinar#1]
Hi Tom,

Thanks so much for the webinar today. I'm asking this question here because I can't find an answer anywhere else...

I can't get any of the `{ojs}` cells to run. They don't cause an error when rendering (either in Rstudio or a command line render). I've copied this repo and re-rendered it producing your html slides, but the `{ojs}` blocks look to be ignored...

<img width="400" alt="image" src="https://user-images.githubusercontent.com/10132972/183765684-8507e3f5-7e5e-45aa-9697-4765154588cc.png">

All of the documentation says Observable is bundled with Quarto, but it seems to rely on Node and a lot of other packages. I've install node on my Mac (`brew install node`) and tried to install the observable standard library (`npm install @observablehq/stdlib`) but still no luck. 

A [comment](https://github.com/quarto-dev/quarto-cli/issues/529#issuecomment-1129295188) from a few months ago says `{ojs}` doesn't even work in Rstudio, but I don't know if that is true anymore. I am, however, still getting that same error when I try to run an `{ojs}` chunk: `/bin/sh: ojs: command not found`. 

I'm not sure what I am missing, please help! Or, if there is a better spot to ask this let me know. I'm running RStudio 2022.07.1 Build 554 on macOS 11.6.7.

Thanks!

**Comment by jeffkimbrel** [comment]
I was able to get it to render properly in VS Code, so there is just something not connecting with Rstudio. I will play around and see why, but it doesn't appear to be any limitations to software I have installed on my machine.

**Comment by jthomasmock** [comment]
Hey! Sorry for delay! 

`ojs` chunks are not able to work interactively line-by-line right now, so you have to:
- `$ quarto preview document.qmd` <- this maintains a temp web server hosting the content and loading observable.js
